-- ════════════════════════════════════════════════════════════════════════════
--  Hireloom · OPTIONAL demo data (users, jobs and job applications)
--
--  Run AFTER schema.sql, in Supabase → SQL Editor. Safe to re-run (existing rows are skipped).
--  Every demo account's password is:  password123
--    Recruiters: maya@northwind.test · arjun@lumen.test
--    Candidates: priya@example.test · daniel@example.test · sofia@example.test · rahul@example.test · aisha@example.test · ethan@example.test
--
--  Resume PDFs for these applications are created in Storage automatically the first time a
--  recruiter or candidate clicks "View resume" — no file upload needed.
--
--  Generated by `npm run db:seed-sql` — edit lib/seed.ts, not this file.
-- ════════════════════════════════════════════════════════════════════════════

insert into public."Bhargavi_Job Portal with role-based login_users" (id, name, email, password_hash, role, created_at) values
  ('usr_recruiter1', 'Maya Chen', 'maya@northwind.test', 'f0258b45592e582636d8a8ff7c7af4c6:4640912d91f0f0024f2e70adcf4cb54925d477d79eb990f898ed36bf0fc1b36933bfea4578ca5a34f1c416819062c0a032e5b854456268ca0e96b522ad0b1d1f', 'recruiter', '2026-07-28T03:39:48.563Z'),
  ('usr_recruiter2', 'Arjun Rao', 'arjun@lumen.test', 'f0258b45592e582636d8a8ff7c7af4c6:4640912d91f0f0024f2e70adcf4cb54925d477d79eb990f898ed36bf0fc1b36933bfea4578ca5a34f1c416819062c0a032e5b854456268ca0e96b522ad0b1d1f', 'recruiter', '2026-08-13T05:09:48.564Z'),
  ('usr_candidate1', 'Priya Sharma', 'priya@example.test', 'f0258b45592e582636d8a8ff7c7af4c6:4640912d91f0f0024f2e70adcf4cb54925d477d79eb990f898ed36bf0fc1b36933bfea4578ca5a34f1c416819062c0a032e5b854456268ca0e96b522ad0b1d1f', 'candidate', '2026-08-29T06:39:48.564Z'),
  ('usr_candidate2', 'Daniel Okafor', 'daniel@example.test', 'f0258b45592e582636d8a8ff7c7af4c6:4640912d91f0f0024f2e70adcf4cb54925d477d79eb990f898ed36bf0fc1b36933bfea4578ca5a34f1c416819062c0a032e5b854456268ca0e96b522ad0b1d1f', 'candidate', '2026-09-03T15:09:48.564Z'),
  ('usr_candidate3', 'Sofia Martins', 'sofia@example.test', 'f0258b45592e582636d8a8ff7c7af4c6:4640912d91f0f0024f2e70adcf4cb54925d477d79eb990f898ed36bf0fc1b36933bfea4578ca5a34f1c416819062c0a032e5b854456268ca0e96b522ad0b1d1f', 'candidate', '2026-09-08T23:39:48.564Z'),
  ('usr_candidate4', 'Rahul Verma', 'rahul@example.test', 'f0258b45592e582636d8a8ff7c7af4c6:4640912d91f0f0024f2e70adcf4cb54925d477d79eb990f898ed36bf0fc1b36933bfea4578ca5a34f1c416819062c0a032e5b854456268ca0e96b522ad0b1d1f', 'candidate', '2026-09-11T03:03:48.564Z'),
  ('usr_candidate5', 'Aisha Khan', 'aisha@example.test', 'f0258b45592e582636d8a8ff7c7af4c6:4640912d91f0f0024f2e70adcf4cb54925d477d79eb990f898ed36bf0fc1b36933bfea4578ca5a34f1c416819062c0a032e5b854456268ca0e96b522ad0b1d1f', 'candidate', '2026-09-14T08:09:48.564Z'),
  ('usr_candidate6', 'Ethan Brooks', 'ethan@example.test', 'f0258b45592e582636d8a8ff7c7af4c6:4640912d91f0f0024f2e70adcf4cb54925d477d79eb990f898ed36bf0fc1b36933bfea4578ca5a34f1c416819062c0a032e5b854456268ca0e96b522ad0b1d1f', 'candidate', '2026-09-17T13:15:48.564Z')
on conflict do nothing;

insert into public."Bhargavi_Job Portal with role-based login_jobs"
  (id, recruiter_id, title, company, description, location, type, salary, status, created_at, updated_at) values
  ('job_senior_fe', 'usr_recruiter1', 'Senior Frontend Engineer', 'Northwind Labs', 'Northwind Labs builds analytics tooling used by 4,000+ product teams. We are looking for a senior frontend engineer to own our visualization layer end-to-end.

What you''ll do
• Lead the architecture of our React + TypeScript dashboard platform
• Ship performant, accessible data visualizations used by millions
• Mentor engineers and raise the bar on code quality and reviews

What we''re looking for
• 5+ years building production web apps
• Deep knowledge of React, TypeScript and modern CSS
• An eye for detail and interaction design

Why you''ll love it here
Hybrid schedule, generous learning budget, top-tier health cover and a team that genuinely cares about craft.', 'Bengaluru', 'Full-time', '₹32–45 LPA', 'open', '2026-09-29T07:57:48.564Z', '2026-09-29T07:57:48.564Z'),
  ('job_product_designer', 'usr_recruiter1', 'Product Designer', 'Northwind Labs', 'Join a small, senior design team shaping how analysts explore data.

What you''ll do
• Own end-to-end design for new product surfaces
• Run research sessions and turn insights into prototypes
• Contribute to our design system

What we''re looking for
• 4+ years of product design experience
• A portfolio showing systems thinking
• Fluency in Figma and prototyping tools

Why you''ll love it here
Fully remote, async-first culture with quarterly offsites.', 'Remote', 'Full-time', '$110k – $140k', 'open', '2026-09-27T04:33:48.564Z', '2026-09-27T04:33:48.564Z'),
  ('job_data_intern', 'usr_recruiter1', 'Data Science Intern', 'Northwind Labs', 'A 6-month internship working alongside our ML team on forecasting models.

What you''ll do
• Clean, explore and model real customer datasets
• Build evaluation pipelines in Python
• Present findings to product leadership

What we''re looking for
• Final-year student or recent graduate
• Solid Python, pandas and statistics foundations
• Curiosity and clear communication

Why you''ll love it here
Mentorship from senior data scientists and a strong conversion path to full-time.', 'Hyderabad', 'Internship', '₹60k / month', 'open', '2026-09-23T23:27:48.564Z', '2026-09-23T23:27:48.564Z'),
  ('job_backend_go', 'usr_recruiter2', 'Backend Engineer (Go)', 'Lumen Pay', 'Lumen Pay processes millions of payments every day. Help us build the reliable, low-latency services behind them.

What you''ll do
• Design and build high-throughput services in Go
• Improve observability and reliability of our payment rails
• Collaborate with product on new payment flows

What we''re looking for
• 3+ years backend experience
• Experience with Go, PostgreSQL and distributed systems
• Comfort owning services in production

Why you''ll love it here
ESOPs, flexible hours, and a modern stack with real scale.', 'Pune', 'Full-time', '₹24–36 LPA', 'open', '2026-09-28T06:15:48.564Z', '2026-09-28T06:15:48.564Z'),
  ('job_devops_contract', 'usr_recruiter2', 'DevOps Engineer', 'Lumen Pay', 'A 6-month contract to modernise our infrastructure-as-code and CI pipelines.

What you''ll do
• Migrate infrastructure to Terraform modules
• Harden Kubernetes clusters and CI/CD pipelines
• Document and hand over runbooks

What we''re looking for
• Strong Terraform, Kubernetes and AWS experience
• Security-first mindset
• Excellent written communication

Why you''ll love it here
Flexible hours and a possible extension.', 'Remote', 'Contract', '$75 – $95 / hr', 'open', '2026-09-26T02:51:48.564Z', '2026-09-26T02:51:48.564Z'),
  ('job_content_pt', 'usr_recruiter2', 'Content Strategist', 'Lumen Pay', 'Shape the voice of a fast-growing fintech brand, 3 days a week.

What you''ll do
• Own our editorial calendar across blog and newsletter
• Write clear, trustworthy product copy
• Measure and iterate on content performance

What we''re looking for
• 3+ years in content or product marketing
• Exceptional writing and editing
• Fintech experience is a plus

Why you''ll love it here
A flexible schedule with a supportive, remote-friendly team.', 'London', 'Part-time', '£35k pro-rata', 'open', '2026-09-21T20:03:48.564Z', '2026-09-21T20:03:48.564Z'),
  ('job_mobile_rn', 'usr_recruiter1', 'Mobile Engineer (React Native)', 'Northwind Labs', 'Bring Northwind insights to iOS and Android with a delightful native experience.

What you''ll do
• Build our React Native app from the ground up
• Work closely with design on motion and interaction
• Set up testing and release automation

What we''re looking for
• 4+ years of mobile development
• Shipped React Native apps to the stores
• Pride in polish and performance

Why you''ll love it here
Equity, relocation support and a beautiful SF office.', 'San Francisco', 'Full-time', '$150k – $185k', 'open', '2026-09-19T16:39:48.564Z', '2026-09-19T16:39:48.564Z'),
  ('job_qa_contract', 'usr_recruiter2', 'QA Automation Engineer', 'Lumen Pay', 'Help us ship faster with confidence by building a robust automated test suite.

What you''ll do
• Build end-to-end tests with Playwright
• Integrate test suites into CI
• Partner with engineers on testability

What we''re looking for
• 3+ years of QA automation
• Playwright or Cypress experience
• Attention to detail

Why you''ll love it here
Clear scope, great team, and hybrid flexibility.', 'Bengaluru', 'Contract', '₹1.8L / month', 'closed', '2026-09-17T13:15:48.564Z', '2026-09-17T13:15:48.564Z')
on conflict do nothing;

insert into public."Bhargavi_Job Portal with role-based login_applications"
  (id, job_id, candidate_id, cover_note, resume_path, resume_name, status, created_at, updated_at) values
  ('app_1', 'job_senior_fe', 'usr_candidate1', 'I have led frontend at two SaaS startups and love building data-heavy interfaces. Would be thrilled to help shape your visualization layer.', 'usr_candidate1/app_1.pdf', 'Priya_Sharma_Resume.pdf', 'shortlisted', '2026-09-29T07:57:48.564Z', '2026-09-29T07:57:48.564Z'),
  ('app_2', 'job_backend_go', 'usr_candidate1', 'Go has been my primary language for 3 years, most recently on a payments reconciliation service.', 'usr_candidate1/app_2.pdf', 'Priya_Sharma_Resume.pdf', 'reviewing', '2026-09-28T06:15:48.564Z', '2026-09-28T06:15:48.564Z'),
  ('app_3', 'job_product_designer', 'usr_candidate1', 'Designer with a strong systems background — portfolio linked in my resume.', 'usr_candidate1/app_3.pdf', 'Priya_Sharma_Resume.pdf', 'applied', '2026-09-27T04:33:48.564Z', '2026-09-27T04:33:48.564Z'),
  ('app_4', 'job_senior_fe', 'usr_candidate2', 'Seven years of React experience, including a large-scale migration to TypeScript.', 'usr_candidate2/app_4.pdf', 'Daniel_Okafor_Resume.pdf', 'reviewing', '2026-09-29T07:57:48.564Z', '2026-09-29T07:57:48.564Z'),
  ('app_5', 'job_senior_fe', 'usr_candidate3', 'Accessibility advocate and frontend engineer — I would love to chat.', 'usr_candidate3/app_5.pdf', 'Sofia_Martins_Resume.pdf', 'applied', '2026-09-30T09:39:48.564Z', '2026-09-30T09:39:48.564Z'),
  ('app_6', 'job_data_intern', 'usr_candidate3', 'Final-year CS student with two Kaggle medals and a passion for forecasting.', 'usr_candidate3/app_6.pdf', 'Sofia_Martins_Resume.pdf', 'shortlisted', '2026-09-25T01:09:48.564Z', '2026-09-25T01:09:48.564Z'),
  ('app_7', 'job_mobile_rn', 'usr_candidate2', 'I have shipped three React Native apps with 100k+ downloads each.', 'usr_candidate2/app_7.pdf', 'Daniel_Okafor_Resume.pdf', 'rejected', '2026-09-20T18:21:48.564Z', '2026-09-20T18:21:48.564Z'),
  ('app_8', 'job_backend_go', 'usr_candidate4', 'Four years building payment services in Go and PostgreSQL, including a ledger that handles 2M transactions a day.', 'usr_candidate4/app_8.pdf', 'Rahul_Verma_Resume.pdf', 'hired', '2026-09-18T14:57:48.564Z', '2026-09-18T14:57:48.564Z'),
  ('app_9', 'job_devops_contract', 'usr_candidate4', 'I have migrated two companies to Terraform and hardened EKS clusters for PCI compliance. Available to start immediately.', 'usr_candidate4/app_9.pdf', 'Rahul_Verma_Resume.pdf', 'reviewing', '2026-09-27T04:33:48.564Z', '2026-09-27T04:33:48.564Z'),
  ('app_10', 'job_content_pt', 'usr_candidate5', 'I write product copy and long-form content for fintech brands, and a three-day week suits me perfectly.', 'usr_candidate5/app_10.pdf', 'Aisha_Khan_Resume.pdf', 'shortlisted', '2026-09-23T23:27:48.564Z', '2026-09-23T23:27:48.564Z'),
  ('app_11', 'job_product_designer', 'usr_candidate5', 'Product designer with a background in content design — I love turning research into clear, simple flows.', 'usr_candidate5/app_11.pdf', 'Aisha_Khan_Resume.pdf', 'reviewing', '2026-09-28T06:15:48.564Z', '2026-09-28T06:15:48.564Z'),
  ('app_12', 'job_data_intern', 'usr_candidate6', 'Final-year student who has built forecasting models for a local retail chain. Keen to learn from your ML team.', 'usr_candidate6/app_12.pdf', 'Ethan_Brooks_Resume.pdf', 'applied', '2026-09-29T07:57:48.564Z', '2026-09-29T07:57:48.564Z'),
  ('app_13', 'job_mobile_rn', 'usr_candidate6', 'Full-stack engineer who has shipped two React Native apps; I care a lot about smooth animations and offline support.', 'usr_candidate6/app_13.pdf', 'Ethan_Brooks_Resume.pdf', 'shortlisted', '2026-09-22T21:45:48.564Z', '2026-09-22T21:45:48.564Z'),
  ('app_14', 'job_qa_contract', 'usr_candidate4', 'I have built Playwright suites from scratch for three product teams and integrated them into CI.', 'usr_candidate4/app_14.pdf', 'Rahul_Verma_Resume.pdf', 'rejected', '2026-09-16T11:33:48.564Z', '2026-09-16T11:33:48.564Z'),
  ('app_15', 'job_content_pt', 'usr_candidate3', 'I run a small newsletter about personal finance and would love to write for Lumen Pay part-time.', 'usr_candidate3/app_15.pdf', 'Sofia_Martins_Resume.pdf', 'applied', '2026-09-30T09:39:48.564Z', '2026-09-30T09:39:48.564Z'),
  ('app_16', 'job_devops_contract', 'usr_candidate6', 'Comfortable with Kubernetes, Terraform and GitHub Actions; happy to work async across time zones.', 'usr_candidate6/app_16.pdf', 'Ethan_Brooks_Resume.pdf', 'applied', '2026-09-28T06:15:48.564Z', '2026-09-28T06:15:48.564Z'),
  ('app_17', 'job_senior_fe', 'usr_candidate6', 'Full-stack engineer with strong React skills and an interest in data visualisation.', 'usr_candidate6/app_17.pdf', 'Ethan_Brooks_Resume.pdf', 'rejected', '2026-09-26T02:51:48.564Z', '2026-09-26T02:51:48.564Z')
on conflict do nothing;
