-- ════════════════════════════════════════════════════════════════════════════
--  Hireloom · OPTIONAL demo data (users + jobs)
--
--  Run AFTER schema.sql, in Supabase → SQL Editor. Safe to re-run (existing rows are skipped).
--  Every demo account's password is:  password123
--    Candidates: priya@example.test · daniel@example.test · sofia@example.test
--    Recruiters: maya@northwind.test · arjun@lumen.test
--
--  Generated by `npm run db:seed-sql` — edit lib/seed.ts, not this file.
-- ════════════════════════════════════════════════════════════════════════════

insert into public."Bhargavi_Job Portal with role-based login_users" (id, name, email, password_hash, role, created_at) values
  ('usr_recruiter1', 'Maya Chen', 'maya@northwind.test', 'bbd92b004a20e4e47dba0a8b0392e133:a9f33069e43d93c04acd6e1326746655a1aaeec179b96cc482549a72eb3f056dd7b3204e557146c1c32d033cf65c5211fa98be240039d6c4106ecc0f76ea06b1', 'recruiter', '2026-07-27T23:54:42.888Z'),
  ('usr_recruiter2', 'Arjun Rao', 'arjun@lumen.test', 'bbd92b004a20e4e47dba0a8b0392e133:a9f33069e43d93c04acd6e1326746655a1aaeec179b96cc482549a72eb3f056dd7b3204e557146c1c32d033cf65c5211fa98be240039d6c4106ecc0f76ea06b1', 'recruiter', '2026-08-13T01:24:42.889Z'),
  ('usr_candidate1', 'Priya Sharma', 'priya@example.test', 'bbd92b004a20e4e47dba0a8b0392e133:a9f33069e43d93c04acd6e1326746655a1aaeec179b96cc482549a72eb3f056dd7b3204e557146c1c32d033cf65c5211fa98be240039d6c4106ecc0f76ea06b1', 'candidate', '2026-08-29T02:54:42.889Z'),
  ('usr_candidate2', 'Daniel Okafor', 'daniel@example.test', 'bbd92b004a20e4e47dba0a8b0392e133:a9f33069e43d93c04acd6e1326746655a1aaeec179b96cc482549a72eb3f056dd7b3204e557146c1c32d033cf65c5211fa98be240039d6c4106ecc0f76ea06b1', 'candidate', '2026-09-03T11:24:42.889Z'),
  ('usr_candidate3', 'Sofia Martins', 'sofia@example.test', 'bbd92b004a20e4e47dba0a8b0392e133:a9f33069e43d93c04acd6e1326746655a1aaeec179b96cc482549a72eb3f056dd7b3204e557146c1c32d033cf65c5211fa98be240039d6c4106ecc0f76ea06b1', 'candidate', '2026-09-08T19:54:42.889Z')
on conflict do nothing;

insert into public."Bhargavi_Job Portal with role-based login_jobs"
  (id, recruiter_id, title, company, description, location, type, salary, status, created_at, updated_at) values
  ('job_senior_fe', 'usr_recruiter1', 'Senior Frontend Engineer', 'Northwind Labs', 'Northwind Labs builds analytics tooling used by 4,000+ product teams. We are looking for a senior frontend engineer to own our visualization layer end-to-end.

What you''ll do
• Lead the architecture of our React + TypeScript dashboard platform
• Ship performant, accessible data visualizations used by millions
• Mentor engineers and raise the bar on code quality and reviews

What we''re looking for
• 5+ years building production web apps
• Deep knowledge of React, TypeScript and modern CSS
• An eye for detail and interaction design

Why you''ll love it here
Hybrid schedule, generous learning budget, top-tier health cover and a team that genuinely cares about craft.', 'Bengaluru', 'Full-time', '₹32–45 LPA', 'open', '2026-09-29T04:12:42.889Z', '2026-09-29T04:12:42.889Z'),
  ('job_product_designer', 'usr_recruiter1', 'Product Designer', 'Northwind Labs', 'Join a small, senior design team shaping how analysts explore data.

What you''ll do
• Own end-to-end design for new product surfaces
• Run research sessions and turn insights into prototypes
• Contribute to our design system

What we''re looking for
• 4+ years of product design experience
• A portfolio showing systems thinking
• Fluency in Figma and prototyping tools

Why you''ll love it here
Fully remote, async-first culture with quarterly offsites.', 'Remote', 'Full-time', '$110k – $140k', 'open', '2026-09-27T00:48:42.889Z', '2026-09-27T00:48:42.889Z'),
  ('job_data_intern', 'usr_recruiter1', 'Data Science Intern', 'Northwind Labs', 'A 6-month internship working alongside our ML team on forecasting models.

What you''ll do
• Clean, explore and model real customer datasets
• Build evaluation pipelines in Python
• Present findings to product leadership

What we''re looking for
• Final-year student or recent graduate
• Solid Python, pandas and statistics foundations
• Curiosity and clear communication

Why you''ll love it here
Mentorship from senior data scientists and a strong conversion path to full-time.', 'Hyderabad', 'Internship', '₹60k / month', 'open', '2026-09-23T19:42:42.889Z', '2026-09-23T19:42:42.889Z'),
  ('job_backend_go', 'usr_recruiter2', 'Backend Engineer (Go)', 'Lumen Pay', 'Lumen Pay processes millions of payments every day. Help us build the reliable, low-latency services behind them.

What you''ll do
• Design and build high-throughput services in Go
• Improve observability and reliability of our payment rails
• Collaborate with product on new payment flows

What we''re looking for
• 3+ years backend experience
• Experience with Go, PostgreSQL and distributed systems
• Comfort owning services in production

Why you''ll love it here
ESOPs, flexible hours, and a modern stack with real scale.', 'Pune', 'Full-time', '₹24–36 LPA', 'open', '2026-09-28T02:30:42.889Z', '2026-09-28T02:30:42.889Z'),
  ('job_devops_contract', 'usr_recruiter2', 'DevOps Engineer', 'Lumen Pay', 'A 6-month contract to modernise our infrastructure-as-code and CI pipelines.

What you''ll do
• Migrate infrastructure to Terraform modules
• Harden Kubernetes clusters and CI/CD pipelines
• Document and hand over runbooks

What we''re looking for
• Strong Terraform, Kubernetes and AWS experience
• Security-first mindset
• Excellent written communication

Why you''ll love it here
Flexible hours and a possible extension.', 'Remote', 'Contract', '$75 – $95 / hr', 'open', '2026-09-25T23:06:42.889Z', '2026-09-25T23:06:42.889Z'),
  ('job_content_pt', 'usr_recruiter2', 'Content Strategist', 'Lumen Pay', 'Shape the voice of a fast-growing fintech brand, 3 days a week.

What you''ll do
• Own our editorial calendar across blog and newsletter
• Write clear, trustworthy product copy
• Measure and iterate on content performance

What we''re looking for
• 3+ years in content or product marketing
• Exceptional writing and editing
• Fintech experience is a plus

Why you''ll love it here
A flexible schedule with a supportive, remote-friendly team.', 'London', 'Part-time', '£35k pro-rata', 'open', '2026-09-21T16:18:42.889Z', '2026-09-21T16:18:42.889Z'),
  ('job_mobile_rn', 'usr_recruiter1', 'Mobile Engineer (React Native)', 'Northwind Labs', 'Bring Northwind insights to iOS and Android with a delightful native experience.

What you''ll do
• Build our React Native app from the ground up
• Work closely with design on motion and interaction
• Set up testing and release automation

What we''re looking for
• 4+ years of mobile development
• Shipped React Native apps to the stores
• Pride in polish and performance

Why you''ll love it here
Equity, relocation support and a beautiful SF office.', 'San Francisco', 'Full-time', '$150k – $185k', 'open', '2026-09-19T12:54:42.889Z', '2026-09-19T12:54:42.889Z'),
  ('job_qa_contract', 'usr_recruiter2', 'QA Automation Engineer', 'Lumen Pay', 'Help us ship faster with confidence by building a robust automated test suite.

What you''ll do
• Build end-to-end tests with Playwright
• Integrate test suites into CI
• Partner with engineers on testability

What we''re looking for
• 3+ years of QA automation
• Playwright or Cypress experience
• Attention to detail

Why you''ll love it here
Clear scope, great team, and hybrid flexibility.', 'Bengaluru', 'Contract', '₹1.8L / month', 'closed', '2026-09-17T09:30:42.889Z', '2026-09-17T09:30:42.889Z')
on conflict do nothing;
