-- ════════════════════════════════════════════════════════════════════════════
--  Hireloom · demo data: users, jobs, candidate profiles, applications,
--  status history and notifications
--
--  Run AFTER schema.sql, in Supabase → SQL Editor. Safe to re-run: rows that already
--  exist are skipped. Demo jobs that already exist get their skills and deadline filled in.
--  Every demo account's password is:  password123
--    Recruiters: maya@northwind.test · arjun@lumen.test
--    Candidates: priya@example.test · daniel@example.test · sofia@example.test · rahul@example.test · aisha@example.test · ethan@example.test
--
--  Resume PDFs are created in Storage automatically the first time someone opens one.
--  Generated by `npm run db:seed-sql` — edit lib/seed.ts, not this file.
-- ════════════════════════════════════════════════════════════════════════════

-- Users
insert into public."Bhargavi_Job Portal with role-based login_users" (id, name, email, password_hash, role, created_at) values
  ('usr_recruiter1', 'Maya Chen', 'maya@northwind.test', 'e6e1af4db9f7dd876c1076d6ebb8a350:7b7556bfdef9b96e0066c79a81803e08e95d16ee12f3e1ff75b3a570c90a29029291eb072a6f75b4206f59043b5581fac4ad3bd92a417fffd3394d0201c28912', 'recruiter', '2026-07-28T05:16:57.667Z'::timestamptz),
  ('usr_recruiter2', 'Arjun Rao', 'arjun@lumen.test', 'e6e1af4db9f7dd876c1076d6ebb8a350:7b7556bfdef9b96e0066c79a81803e08e95d16ee12f3e1ff75b3a570c90a29029291eb072a6f75b4206f59043b5581fac4ad3bd92a417fffd3394d0201c28912', 'recruiter', '2026-08-13T06:46:57.667Z'::timestamptz),
  ('usr_candidate1', 'Priya Sharma', 'priya@example.test', 'e6e1af4db9f7dd876c1076d6ebb8a350:7b7556bfdef9b96e0066c79a81803e08e95d16ee12f3e1ff75b3a570c90a29029291eb072a6f75b4206f59043b5581fac4ad3bd92a417fffd3394d0201c28912', 'candidate', '2026-08-29T08:16:57.667Z'::timestamptz),
  ('usr_candidate2', 'Daniel Okafor', 'daniel@example.test', 'e6e1af4db9f7dd876c1076d6ebb8a350:7b7556bfdef9b96e0066c79a81803e08e95d16ee12f3e1ff75b3a570c90a29029291eb072a6f75b4206f59043b5581fac4ad3bd92a417fffd3394d0201c28912', 'candidate', '2026-09-03T16:46:57.667Z'::timestamptz),
  ('usr_candidate3', 'Sofia Martins', 'sofia@example.test', 'e6e1af4db9f7dd876c1076d6ebb8a350:7b7556bfdef9b96e0066c79a81803e08e95d16ee12f3e1ff75b3a570c90a29029291eb072a6f75b4206f59043b5581fac4ad3bd92a417fffd3394d0201c28912', 'candidate', '2026-09-09T01:16:57.667Z'::timestamptz),
  ('usr_candidate4', 'Rahul Verma', 'rahul@example.test', 'e6e1af4db9f7dd876c1076d6ebb8a350:7b7556bfdef9b96e0066c79a81803e08e95d16ee12f3e1ff75b3a570c90a29029291eb072a6f75b4206f59043b5581fac4ad3bd92a417fffd3394d0201c28912', 'candidate', '2026-09-11T04:40:57.667Z'::timestamptz),
  ('usr_candidate5', 'Aisha Khan', 'aisha@example.test', 'e6e1af4db9f7dd876c1076d6ebb8a350:7b7556bfdef9b96e0066c79a81803e08e95d16ee12f3e1ff75b3a570c90a29029291eb072a6f75b4206f59043b5581fac4ad3bd92a417fffd3394d0201c28912', 'candidate', '2026-09-14T09:46:57.668Z'::timestamptz),
  ('usr_candidate6', 'Ethan Brooks', 'ethan@example.test', 'e6e1af4db9f7dd876c1076d6ebb8a350:7b7556bfdef9b96e0066c79a81803e08e95d16ee12f3e1ff75b3a570c90a29029291eb072a6f75b4206f59043b5581fac4ad3bd92a417fffd3394d0201c28912', 'candidate', '2026-09-17T14:52:57.668Z'::timestamptz)
on conflict do nothing;

-- Jobs (existing demo jobs keep their data; only missing skills/deadline are filled in)
insert into public."Bhargavi_Job Portal with role-based login_jobs"
  (id, recruiter_id, title, company, description, location, type, salary, skills, deadline, status, created_at, updated_at) values
  ('job_senior_fe', 'usr_recruiter1', 'Senior Frontend Engineer', 'Northwind Labs', 'Northwind Labs builds analytics tooling used by 4,000+ product teams. We are looking for a senior frontend engineer to own our visualization layer end-to-end.

What you''ll do
• Lead the architecture of our React + TypeScript dashboard platform
• Ship performant, accessible data visualizations used by millions
• Mentor engineers and raise the bar on code quality and reviews

What we''re looking for
• 5+ years building production web apps
• Deep knowledge of React, TypeScript and modern CSS
• An eye for detail and interaction design

Why you''ll love it here
Hybrid schedule, generous learning budget, top-tier health cover and a team that genuinely cares about craft.', 'Bengaluru', 'Full-time', '₹32–45 LPA', array['React', 'TypeScript', 'Next.js', 'CSS', 'Accessibility']::text[], '2026-10-21'::date, 'open', '2026-09-29T09:34:57.668Z'::timestamptz, '2026-09-29T09:34:57.668Z'::timestamptz),
  ('job_product_designer', 'usr_recruiter1', 'Product Designer', 'Northwind Labs', 'Join a small, senior design team shaping how analysts explore data.

What you''ll do
• Own end-to-end design for new product surfaces
• Run research sessions and turn insights into prototypes
• Contribute to our design system

What we''re looking for
• 4+ years of product design experience
• A portfolio showing systems thinking
• Fluency in Figma and prototyping tools

Why you''ll love it here
Fully remote, async-first culture with quarterly offsites.', 'Remote', 'Full-time', '$110k – $140k', array['Figma', 'User Research', 'Prototyping', 'Design Systems']::text[], '2026-10-14'::date, 'open', '2026-09-27T06:10:57.668Z'::timestamptz, '2026-09-27T06:10:57.668Z'::timestamptz),
  ('job_data_intern', 'usr_recruiter1', 'Data Science Intern', 'Northwind Labs', 'A 6-month internship working alongside our ML team on forecasting models.

What you''ll do
• Clean, explore and model real customer datasets
• Build evaluation pipelines in Python
• Present findings to product leadership

What we''re looking for
• Final-year student or recent graduate
• Solid Python, pandas and statistics foundations
• Curiosity and clear communication

Why you''ll love it here
Mentorship from senior data scientists and a strong conversion path to full-time.', 'Hyderabad', 'Internship', '₹60k / month', array['Python', 'pandas', 'SQL', 'Statistics']::text[], '2026-10-30'::date, 'open', '2026-09-24T01:04:57.668Z'::timestamptz, '2026-09-24T01:04:57.668Z'::timestamptz),
  ('job_backend_go', 'usr_recruiter2', 'Backend Engineer (Go)', 'Lumen Pay', 'Lumen Pay processes millions of payments every day. Help us build the reliable, low-latency services behind them.

What you''ll do
• Design and build high-throughput services in Go
• Improve observability and reliability of our payment rails
• Collaborate with product on new payment flows

What we''re looking for
• 3+ years backend experience
• Experience with Go, PostgreSQL and distributed systems
• Comfort owning services in production

Why you''ll love it here
ESOPs, flexible hours, and a modern stack with real scale.', 'Pune', 'Full-time', '₹24–36 LPA', array['Go', 'PostgreSQL', 'Docker', 'Distributed Systems']::text[], '2026-10-18'::date, 'open', '2026-09-28T07:52:57.668Z'::timestamptz, '2026-09-28T07:52:57.668Z'::timestamptz),
  ('job_devops_contract', 'usr_recruiter2', 'DevOps Engineer', 'Lumen Pay', 'A 6-month contract to modernise our infrastructure-as-code and CI pipelines.

What you''ll do
• Migrate infrastructure to Terraform modules
• Harden Kubernetes clusters and CI/CD pipelines
• Document and hand over runbooks

What we''re looking for
• Strong Terraform, Kubernetes and AWS experience
• Security-first mindset
• Excellent written communication

Why you''ll love it here
Flexible hours and a possible extension.', 'Remote', 'Contract', '$75 – $95 / hr', array['Terraform', 'Kubernetes', 'AWS', 'CI/CD']::text[], '2026-10-10'::date, 'open', '2026-09-26T04:28:57.668Z'::timestamptz, '2026-09-26T04:28:57.668Z'::timestamptz),
  ('job_content_pt', 'usr_recruiter2', 'Content Strategist', 'Lumen Pay', 'Shape the voice of a fast-growing fintech brand, 3 days a week.

What you''ll do
• Own our editorial calendar across blog and newsletter
• Write clear, trustworthy product copy
• Measure and iterate on content performance

What we''re looking for
• 3+ years in content or product marketing
• Exceptional writing and editing
• Fintech experience is a plus

Why you''ll love it here
A flexible schedule with a supportive, remote-friendly team.', 'London', 'Part-time', '£35k pro-rata', array['Content Strategy', 'Copywriting', 'SEO', 'Fintech']::text[], '2026-09-28'::date, 'open', '2026-09-21T21:40:57.668Z'::timestamptz, '2026-09-21T21:40:57.668Z'::timestamptz),
  ('job_mobile_rn', 'usr_recruiter1', 'Mobile Engineer (React Native)', 'Northwind Labs', 'Bring Northwind insights to iOS and Android with a delightful native experience.

What you''ll do
• Build our React Native app from the ground up
• Work closely with design on motion and interaction
• Set up testing and release automation

What we''re looking for
• 4+ years of mobile development
• Shipped React Native apps to the stores
• Pride in polish and performance

Why you''ll love it here
Equity, relocation support and a beautiful SF office.', 'San Francisco', 'Full-time', '$150k – $185k', array['React Native', 'TypeScript', 'iOS', 'Android']::text[], '2026-10-25'::date, 'open', '2026-09-19T18:16:57.668Z'::timestamptz, '2026-09-19T18:16:57.668Z'::timestamptz),
  ('job_qa_contract', 'usr_recruiter2', 'QA Automation Engineer', 'Lumen Pay', 'Help us ship faster with confidence by building a robust automated test suite.

What you''ll do
• Build end-to-end tests with Playwright
• Integrate test suites into CI
• Partner with engineers on testability

What we''re looking for
• 3+ years of QA automation
• Playwright or Cypress experience
• Attention to detail

Why you''ll love it here
Clear scope, great team, and hybrid flexibility.', 'Bengaluru', 'Contract', '₹1.8L / month', array['Playwright', 'JavaScript', 'CI/CD', 'Testing']::text[], '2026-09-25'::date, 'closed', '2026-09-17T14:52:57.668Z'::timestamptz, '2026-09-17T14:52:57.668Z'::timestamptz)
on conflict (id) do update set
  skills   = case when cardinality(public."Bhargavi_Job Portal with role-based login_jobs".skills) = 0 then excluded.skills else public."Bhargavi_Job Portal with role-based login_jobs".skills end,
  deadline = coalesce(public."Bhargavi_Job Portal with role-based login_jobs".deadline, excluded.deadline);

-- Candidate profiles
insert into public."Bhargavi_Job Portal with role-based login_candidate_profiles"
  (user_id, phone, skills, years_experience, resume_path, resume_name, resume_size, updated_at)
select v.* from (values
  ('usr_candidate1', '+91 98450 11223', array['React', 'TypeScript', 'Next.js', 'CSS', 'D3', 'Go']::text[], 7, 'usr_candidate1/profile.pdf', 'Priya_Sharma_Resume.pdf', 1800, '2026-08-29T08:16:57.667Z'::timestamptz),
  ('usr_candidate2', '+234 803 555 0142', array['React', 'React Native', 'TypeScript', 'iOS', 'Jest']::text[], 8, 'usr_candidate2/profile.pdf', 'Daniel_Okafor_Resume.pdf', 1800, '2026-09-03T16:46:57.667Z'::timestamptz),
  ('usr_candidate3', '+351 912 345 678', array['Python', 'pandas', 'SQL', 'Accessibility', 'Copywriting']::text[], 1, 'usr_candidate3/profile.pdf', 'Sofia_Martins_Resume.pdf', 1800, '2026-09-09T01:16:57.667Z'::timestamptz),
  ('usr_candidate4', '+91 99200 44556', array['Go', 'PostgreSQL', 'Docker', 'Kubernetes', 'Terraform', 'AWS', 'Playwright']::text[], 6, 'usr_candidate4/profile.pdf', 'Rahul_Verma_Resume.pdf', 1800, '2026-09-11T04:40:57.667Z'::timestamptz),
  ('usr_candidate5', '+91 98110 77889', array['Figma', 'User Research', 'Prototyping', 'Copywriting', 'Content Strategy']::text[], 5, 'usr_candidate5/profile.pdf', 'Aisha_Khan_Resume.pdf', 1800, '2026-09-14T09:46:57.668Z'::timestamptz),
  ('usr_candidate6', '+44 7700 900123', array['TypeScript', 'React Native', 'Node.js', 'Python', 'Kubernetes', 'CI/CD']::text[], 4, 'usr_candidate6/profile.pdf', 'Ethan_Brooks_Resume.pdf', 1800, '2026-09-17T14:52:57.668Z'::timestamptz)
) as v(user_id, phone, skills, years_experience, resume_path, resume_name, resume_size, updated_at)
where exists (select 1 from public."Bhargavi_Job Portal with role-based login_users" u where u.id = v.user_id)
on conflict do nothing;

-- Applications
insert into public."Bhargavi_Job Portal with role-based login_applications"
  (id, job_id, candidate_id, cover_note, resume_path, resume_name, status, applied_on, updated_at) values
  ('app_1', 'job_senior_fe', 'usr_candidate1', 'I have led frontend at two SaaS startups and love building data-heavy interfaces. Would be thrilled to help shape your visualization layer.', 'usr_candidate1/app_1.pdf', 'Priya_Sharma_Resume.pdf', 'interview', '2026-09-29T09:34:57.668Z'::timestamptz, '2026-09-30T10:16:57.668Z'::timestamptz),
  ('app_2', 'job_backend_go', 'usr_candidate1', 'Go has been my primary language for 3 years, most recently on a payments reconciliation service.', 'usr_candidate1/app_2.pdf', 'Priya_Sharma_Resume.pdf', 'shortlisted', '2026-09-28T07:52:57.668Z'::timestamptz, '2026-09-30T10:16:57.669Z'::timestamptz),
  ('app_3', 'job_product_designer', 'usr_candidate1', 'Designer with a strong systems background — portfolio linked in my resume.', 'usr_candidate1/app_3.pdf', 'Priya_Sharma_Resume.pdf', 'applied', '2026-09-27T06:10:57.668Z'::timestamptz, '2026-09-27T06:10:57.668Z'::timestamptz),
  ('app_4', 'job_senior_fe', 'usr_candidate2', 'Seven years of React experience, including a large-scale migration to TypeScript.', 'usr_candidate2/app_4.pdf', 'Daniel_Okafor_Resume.pdf', 'shortlisted', '2026-09-29T09:34:57.668Z'::timestamptz, '2026-09-30T10:16:57.669Z'::timestamptz),
  ('app_5', 'job_senior_fe', 'usr_candidate3', 'Accessibility advocate and frontend engineer — I would love to chat.', 'usr_candidate3/app_5.pdf', 'Sofia_Martins_Resume.pdf', 'applied', '2026-09-30T11:16:57.668Z'::timestamptz, '2026-09-30T11:16:57.668Z'::timestamptz),
  ('app_6', 'job_data_intern', 'usr_candidate3', 'Final-year CS student with two Kaggle medals and a passion for forecasting.', 'usr_candidate3/app_6.pdf', 'Sofia_Martins_Resume.pdf', 'interview', '2026-09-25T02:46:57.668Z'::timestamptz, '2026-09-28T08:46:57.668Z'::timestamptz),
  ('app_7', 'job_mobile_rn', 'usr_candidate2', 'I have shipped three React Native apps with 100k+ downloads each.', 'usr_candidate2/app_7.pdf', 'Daniel_Okafor_Resume.pdf', 'rejected', '2026-09-20T19:58:57.668Z'::timestamptz, '2026-09-24T01:58:57.668Z'::timestamptz),
  ('app_8', 'job_backend_go', 'usr_candidate4', 'Four years building payment services in Go and PostgreSQL, including a ledger that handles 2M transactions a day.', 'usr_candidate4/app_8.pdf', 'Rahul_Verma_Resume.pdf', 'offered', '2026-09-18T16:34:57.668Z'::timestamptz, '2026-09-23T00:34:57.668Z'::timestamptz),
  ('app_9', 'job_devops_contract', 'usr_candidate4', 'I have migrated two companies to Terraform and hardened EKS clusters for PCI compliance. Available to start immediately.', 'usr_candidate4/app_9.pdf', 'Rahul_Verma_Resume.pdf', 'shortlisted', '2026-09-27T06:10:57.668Z'::timestamptz, '2026-09-29T10:10:57.668Z'::timestamptz),
  ('app_10', 'job_content_pt', 'usr_candidate5', 'I write product copy and long-form content for fintech brands, and a three-day week suits me perfectly.', 'usr_candidate5/app_10.pdf', 'Aisha_Khan_Resume.pdf', 'interview', '2026-09-24T01:04:57.668Z'::timestamptz, '2026-09-27T07:04:57.668Z'::timestamptz),
  ('app_11', 'job_product_designer', 'usr_candidate5', 'Product designer with a background in content design — I love turning research into clear, simple flows.', 'usr_candidate5/app_11.pdf', 'Aisha_Khan_Resume.pdf', 'shortlisted', '2026-09-28T07:52:57.668Z'::timestamptz, '2026-09-30T10:16:57.669Z'::timestamptz),
  ('app_12', 'job_data_intern', 'usr_candidate6', 'Final-year student who has built forecasting models for a local retail chain. Keen to learn from your ML team.', 'usr_candidate6/app_12.pdf', 'Ethan_Brooks_Resume.pdf', 'applied', '2026-09-29T09:34:57.668Z'::timestamptz, '2026-09-29T09:34:57.668Z'::timestamptz),
  ('app_13', 'job_mobile_rn', 'usr_candidate6', 'Full-stack engineer who has shipped two React Native apps; I care a lot about smooth animations and offline support.', 'usr_candidate6/app_13.pdf', 'Ethan_Brooks_Resume.pdf', 'interview', '2026-09-22T23:22:57.668Z'::timestamptz, '2026-09-26T05:22:57.668Z'::timestamptz),
  ('app_14', 'job_qa_contract', 'usr_candidate4', 'I have built Playwright suites from scratch for three product teams and integrated them into CI.', 'usr_candidate4/app_14.pdf', 'Rahul_Verma_Resume.pdf', 'rejected', '2026-09-16T13:10:57.668Z'::timestamptz, '2026-09-18T17:10:57.668Z'::timestamptz),
  ('app_15', 'job_content_pt', 'usr_candidate3', 'I run a small newsletter about personal finance and would love to write for Lumen Pay part-time.', 'usr_candidate3/app_15.pdf', 'Sofia_Martins_Resume.pdf', 'applied', '2026-09-30T11:16:57.668Z'::timestamptz, '2026-09-30T11:16:57.668Z'::timestamptz),
  ('app_16', 'job_devops_contract', 'usr_candidate6', 'Comfortable with Kubernetes, Terraform and GitHub Actions; happy to work async across time zones.', 'usr_candidate6/app_16.pdf', 'Ethan_Brooks_Resume.pdf', 'applied', '2026-09-28T07:52:57.668Z'::timestamptz, '2026-09-28T07:52:57.668Z'::timestamptz),
  ('app_17', 'job_senior_fe', 'usr_candidate6', 'Full-stack engineer with strong React skills and an interest in data visualisation.', 'usr_candidate6/app_17.pdf', 'Ethan_Brooks_Resume.pdf', 'rejected', '2026-09-26T04:28:57.668Z'::timestamptz, '2026-09-28T08:28:57.668Z'::timestamptz)
on conflict do nothing;

-- Status history (only for applications that exist)
insert into public."Bhargavi_Job Portal with role-based login_status_history" (id, application_id, from_status, to_status, changed_by, changed_at)
select v.* from (values
  ('hist_app_1_0', 'app_1', null, 'applied', 'usr_candidate1', '2026-09-29T09:34:57.668Z'::timestamptz),
  ('hist_app_1_1', 'app_1', 'applied', 'shortlisted', 'usr_recruiter1', '2026-09-29T21:55:57.668Z'::timestamptz),
  ('hist_app_1_2', 'app_1', 'shortlisted', 'interview', 'usr_recruiter1', '2026-09-30T10:16:57.668Z'::timestamptz),
  ('hist_app_2_0', 'app_2', null, 'applied', 'usr_candidate1', '2026-09-28T07:52:57.668Z'::timestamptz),
  ('hist_app_2_1', 'app_2', 'applied', 'shortlisted', 'usr_recruiter2', '2026-09-30T10:16:57.669Z'::timestamptz),
  ('hist_app_3_0', 'app_3', null, 'applied', 'usr_candidate1', '2026-09-27T06:10:57.668Z'::timestamptz),
  ('hist_app_4_0', 'app_4', null, 'applied', 'usr_candidate2', '2026-09-29T09:34:57.668Z'::timestamptz),
  ('hist_app_4_1', 'app_4', 'applied', 'shortlisted', 'usr_recruiter1', '2026-09-30T10:16:57.669Z'::timestamptz),
  ('hist_app_5_0', 'app_5', null, 'applied', 'usr_candidate3', '2026-09-30T11:16:57.668Z'::timestamptz),
  ('hist_app_6_0', 'app_6', null, 'applied', 'usr_candidate3', '2026-09-25T02:46:57.668Z'::timestamptz),
  ('hist_app_6_1', 'app_6', 'applied', 'shortlisted', 'usr_recruiter1', '2026-09-26T17:46:57.668Z'::timestamptz),
  ('hist_app_6_2', 'app_6', 'shortlisted', 'interview', 'usr_recruiter1', '2026-09-28T08:46:57.668Z'::timestamptz),
  ('hist_app_7_0', 'app_7', null, 'applied', 'usr_candidate2', '2026-09-20T19:58:57.668Z'::timestamptz),
  ('hist_app_7_1', 'app_7', 'applied', 'shortlisted', 'usr_recruiter1', '2026-09-22T10:58:57.668Z'::timestamptz),
  ('hist_app_7_2', 'app_7', 'shortlisted', 'rejected', 'usr_recruiter1', '2026-09-24T01:58:57.668Z'::timestamptz),
  ('hist_app_8_0', 'app_8', null, 'applied', 'usr_candidate4', '2026-09-18T16:34:57.668Z'::timestamptz),
  ('hist_app_8_1', 'app_8', 'applied', 'shortlisted', 'usr_recruiter2', '2026-09-20T03:14:57.668Z'::timestamptz),
  ('hist_app_8_2', 'app_8', 'shortlisted', 'interview', 'usr_recruiter2', '2026-09-21T13:54:57.668Z'::timestamptz),
  ('hist_app_8_3', 'app_8', 'interview', 'offered', 'usr_recruiter2', '2026-09-23T00:34:57.668Z'::timestamptz),
  ('hist_app_9_0', 'app_9', null, 'applied', 'usr_candidate4', '2026-09-27T06:10:57.668Z'::timestamptz),
  ('hist_app_9_1', 'app_9', 'applied', 'shortlisted', 'usr_recruiter2', '2026-09-29T10:10:57.668Z'::timestamptz),
  ('hist_app_10_0', 'app_10', null, 'applied', 'usr_candidate5', '2026-09-24T01:04:57.668Z'::timestamptz),
  ('hist_app_10_1', 'app_10', 'applied', 'shortlisted', 'usr_recruiter2', '2026-09-25T16:04:57.668Z'::timestamptz),
  ('hist_app_10_2', 'app_10', 'shortlisted', 'interview', 'usr_recruiter2', '2026-09-27T07:04:57.668Z'::timestamptz),
  ('hist_app_11_0', 'app_11', null, 'applied', 'usr_candidate5', '2026-09-28T07:52:57.668Z'::timestamptz),
  ('hist_app_11_1', 'app_11', 'applied', 'shortlisted', 'usr_recruiter1', '2026-09-30T10:16:57.669Z'::timestamptz),
  ('hist_app_12_0', 'app_12', null, 'applied', 'usr_candidate6', '2026-09-29T09:34:57.668Z'::timestamptz),
  ('hist_app_13_0', 'app_13', null, 'applied', 'usr_candidate6', '2026-09-22T23:22:57.668Z'::timestamptz),
  ('hist_app_13_1', 'app_13', 'applied', 'shortlisted', 'usr_recruiter1', '2026-09-24T14:22:57.668Z'::timestamptz),
  ('hist_app_13_2', 'app_13', 'shortlisted', 'interview', 'usr_recruiter1', '2026-09-26T05:22:57.668Z'::timestamptz),
  ('hist_app_14_0', 'app_14', null, 'applied', 'usr_candidate4', '2026-09-16T13:10:57.668Z'::timestamptz),
  ('hist_app_14_1', 'app_14', 'applied', 'rejected', 'usr_recruiter2', '2026-09-18T17:10:57.668Z'::timestamptz),
  ('hist_app_15_0', 'app_15', null, 'applied', 'usr_candidate3', '2026-09-30T11:16:57.668Z'::timestamptz),
  ('hist_app_16_0', 'app_16', null, 'applied', 'usr_candidate6', '2026-09-28T07:52:57.668Z'::timestamptz),
  ('hist_app_17_0', 'app_17', null, 'applied', 'usr_candidate6', '2026-09-26T04:28:57.668Z'::timestamptz),
  ('hist_app_17_1', 'app_17', 'applied', 'rejected', 'usr_recruiter1', '2026-09-28T08:28:57.668Z'::timestamptz)
) as v(id, application_id, from_status, to_status, changed_by, changed_at)
where exists (select 1 from public."Bhargavi_Job Portal with role-based login_applications" a where a.id = v.application_id)
  and not exists (select 1 from public."Bhargavi_Job Portal with role-based login_status_history" h where h.application_id = v.application_id and h.to_status = v.to_status)
on conflict do nothing;

-- Notifications (email-style log)
insert into public."Bhargavi_Job Portal with role-based login_notifications" (id, user_id, to_email, subject, body, application_id, created_at)
select v.* from (values
  ('ntf_app_1_1', 'usr_candidate1', 'priya@example.test', 'You''ve been shortlisted for Senior Frontend Engineer', 'Hi Priya,

Good news — Northwind Labs has shortlisted your application. They will be in touch about next steps.

You can follow every update in My Applications on Hireloom.', 'app_1', '2026-09-29T21:55:57.668Z'::timestamptz),
  ('ntf_app_1_2', 'usr_candidate1', 'priya@example.test', 'Interview stage: Senior Frontend Engineer', 'Hi Priya,

Northwind Labs would like to interview you. Expect a message from the recruiter to arrange a time.

You can follow every update in My Applications on Hireloom.', 'app_1', '2026-09-30T10:16:57.668Z'::timestamptz),
  ('ntf_app_1_new', 'usr_recruiter1', 'maya@northwind.test', 'New application: Priya Sharma for Senior Frontend Engineer', 'Hi Maya,

Priya Sharma applied for Senior Frontend Engineer. Open My Jobs → View applicants to read their cover note and resume.', 'app_1', '2026-09-29T09:34:57.668Z'::timestamptz),
  ('ntf_app_2_1', 'usr_candidate1', 'priya@example.test', 'You''ve been shortlisted for Backend Engineer (Go)', 'Hi Priya,

Good news — Lumen Pay has shortlisted your application. They will be in touch about next steps.

You can follow every update in My Applications on Hireloom.', 'app_2', '2026-09-30T10:16:57.669Z'::timestamptz),
  ('ntf_app_2_new', 'usr_recruiter2', 'arjun@lumen.test', 'New application: Priya Sharma for Backend Engineer (Go)', 'Hi Arjun,

Priya Sharma applied for Backend Engineer (Go). Open My Jobs → View applicants to read their cover note and resume.', 'app_2', '2026-09-28T07:52:57.668Z'::timestamptz),
  ('ntf_app_3_new', 'usr_recruiter1', 'maya@northwind.test', 'New application: Priya Sharma for Product Designer', 'Hi Maya,

Priya Sharma applied for Product Designer. Open My Jobs → View applicants to read their cover note and resume.', 'app_3', '2026-09-27T06:10:57.668Z'::timestamptz),
  ('ntf_app_4_1', 'usr_candidate2', 'daniel@example.test', 'You''ve been shortlisted for Senior Frontend Engineer', 'Hi Daniel,

Good news — Northwind Labs has shortlisted your application. They will be in touch about next steps.

You can follow every update in My Applications on Hireloom.', 'app_4', '2026-09-30T10:16:57.669Z'::timestamptz),
  ('ntf_app_4_new', 'usr_recruiter1', 'maya@northwind.test', 'New application: Daniel Okafor for Senior Frontend Engineer', 'Hi Maya,

Daniel Okafor applied for Senior Frontend Engineer. Open My Jobs → View applicants to read their cover note and resume.', 'app_4', '2026-09-29T09:34:57.668Z'::timestamptz),
  ('ntf_app_5_new', 'usr_recruiter1', 'maya@northwind.test', 'New application: Sofia Martins for Senior Frontend Engineer', 'Hi Maya,

Sofia Martins applied for Senior Frontend Engineer. Open My Jobs → View applicants to read their cover note and resume.', 'app_5', '2026-09-30T11:16:57.668Z'::timestamptz),
  ('ntf_app_6_1', 'usr_candidate3', 'sofia@example.test', 'You''ve been shortlisted for Data Science Intern', 'Hi Sofia,

Good news — Northwind Labs has shortlisted your application. They will be in touch about next steps.

You can follow every update in My Applications on Hireloom.', 'app_6', '2026-09-26T17:46:57.668Z'::timestamptz),
  ('ntf_app_6_2', 'usr_candidate3', 'sofia@example.test', 'Interview stage: Data Science Intern', 'Hi Sofia,

Northwind Labs would like to interview you. Expect a message from the recruiter to arrange a time.

You can follow every update in My Applications on Hireloom.', 'app_6', '2026-09-28T08:46:57.668Z'::timestamptz),
  ('ntf_app_6_new', 'usr_recruiter1', 'maya@northwind.test', 'New application: Sofia Martins for Data Science Intern', 'Hi Maya,

Sofia Martins applied for Data Science Intern. Open My Jobs → View applicants to read their cover note and resume.', 'app_6', '2026-09-25T02:46:57.668Z'::timestamptz),
  ('ntf_app_7_1', 'usr_candidate2', 'daniel@example.test', 'You''ve been shortlisted for Mobile Engineer (React Native)', 'Hi Daniel,

Good news — Northwind Labs has shortlisted your application. They will be in touch about next steps.

You can follow every update in My Applications on Hireloom.', 'app_7', '2026-09-22T10:58:57.668Z'::timestamptz),
  ('ntf_app_7_2', 'usr_candidate2', 'daniel@example.test', 'Update on your application for Mobile Engineer (React Native)', 'Hi Daniel,

Thank you for applying. Northwind Labs has decided not to move forward with your application this time.

You can follow every update in My Applications on Hireloom.', 'app_7', '2026-09-24T01:58:57.668Z'::timestamptz),
  ('ntf_app_7_new', 'usr_recruiter1', 'maya@northwind.test', 'New application: Daniel Okafor for Mobile Engineer (React Native)', 'Hi Maya,

Daniel Okafor applied for Mobile Engineer (React Native). Open My Jobs → View applicants to read their cover note and resume.', 'app_7', '2026-09-20T19:58:57.668Z'::timestamptz),
  ('ntf_app_8_1', 'usr_candidate4', 'rahul@example.test', 'You''ve been shortlisted for Backend Engineer (Go)', 'Hi Rahul,

Good news — Lumen Pay has shortlisted your application. They will be in touch about next steps.

You can follow every update in My Applications on Hireloom.', 'app_8', '2026-09-20T03:14:57.668Z'::timestamptz),
  ('ntf_app_8_2', 'usr_candidate4', 'rahul@example.test', 'Interview stage: Backend Engineer (Go)', 'Hi Rahul,

Lumen Pay would like to interview you. Expect a message from the recruiter to arrange a time.

You can follow every update in My Applications on Hireloom.', 'app_8', '2026-09-21T13:54:57.668Z'::timestamptz),
  ('ntf_app_8_3', 'usr_candidate4', 'rahul@example.test', 'Offer for Backend Engineer (Go)', 'Hi Rahul,

Congratulations! Lumen Pay has decided to offer you the Backend Engineer (Go) role.

You can follow every update in My Applications on Hireloom.', 'app_8', '2026-09-23T00:34:57.668Z'::timestamptz),
  ('ntf_app_8_new', 'usr_recruiter2', 'arjun@lumen.test', 'New application: Rahul Verma for Backend Engineer (Go)', 'Hi Arjun,

Rahul Verma applied for Backend Engineer (Go). Open My Jobs → View applicants to read their cover note and resume.', 'app_8', '2026-09-18T16:34:57.668Z'::timestamptz),
  ('ntf_app_9_1', 'usr_candidate4', 'rahul@example.test', 'You''ve been shortlisted for DevOps Engineer', 'Hi Rahul,

Good news — Lumen Pay has shortlisted your application. They will be in touch about next steps.

You can follow every update in My Applications on Hireloom.', 'app_9', '2026-09-29T10:10:57.668Z'::timestamptz),
  ('ntf_app_9_new', 'usr_recruiter2', 'arjun@lumen.test', 'New application: Rahul Verma for DevOps Engineer', 'Hi Arjun,

Rahul Verma applied for DevOps Engineer. Open My Jobs → View applicants to read their cover note and resume.', 'app_9', '2026-09-27T06:10:57.668Z'::timestamptz),
  ('ntf_app_10_1', 'usr_candidate5', 'aisha@example.test', 'You''ve been shortlisted for Content Strategist', 'Hi Aisha,

Good news — Lumen Pay has shortlisted your application. They will be in touch about next steps.

You can follow every update in My Applications on Hireloom.', 'app_10', '2026-09-25T16:04:57.668Z'::timestamptz),
  ('ntf_app_10_2', 'usr_candidate5', 'aisha@example.test', 'Interview stage: Content Strategist', 'Hi Aisha,

Lumen Pay would like to interview you. Expect a message from the recruiter to arrange a time.

You can follow every update in My Applications on Hireloom.', 'app_10', '2026-09-27T07:04:57.668Z'::timestamptz),
  ('ntf_app_10_new', 'usr_recruiter2', 'arjun@lumen.test', 'New application: Aisha Khan for Content Strategist', 'Hi Arjun,

Aisha Khan applied for Content Strategist. Open My Jobs → View applicants to read their cover note and resume.', 'app_10', '2026-09-24T01:04:57.668Z'::timestamptz),
  ('ntf_app_11_1', 'usr_candidate5', 'aisha@example.test', 'You''ve been shortlisted for Product Designer', 'Hi Aisha,

Good news — Northwind Labs has shortlisted your application. They will be in touch about next steps.

You can follow every update in My Applications on Hireloom.', 'app_11', '2026-09-30T10:16:57.669Z'::timestamptz),
  ('ntf_app_11_new', 'usr_recruiter1', 'maya@northwind.test', 'New application: Aisha Khan for Product Designer', 'Hi Maya,

Aisha Khan applied for Product Designer. Open My Jobs → View applicants to read their cover note and resume.', 'app_11', '2026-09-28T07:52:57.668Z'::timestamptz),
  ('ntf_app_12_new', 'usr_recruiter1', 'maya@northwind.test', 'New application: Ethan Brooks for Data Science Intern', 'Hi Maya,

Ethan Brooks applied for Data Science Intern. Open My Jobs → View applicants to read their cover note and resume.', 'app_12', '2026-09-29T09:34:57.668Z'::timestamptz),
  ('ntf_app_13_1', 'usr_candidate6', 'ethan@example.test', 'You''ve been shortlisted for Mobile Engineer (React Native)', 'Hi Ethan,

Good news — Northwind Labs has shortlisted your application. They will be in touch about next steps.

You can follow every update in My Applications on Hireloom.', 'app_13', '2026-09-24T14:22:57.668Z'::timestamptz),
  ('ntf_app_13_2', 'usr_candidate6', 'ethan@example.test', 'Interview stage: Mobile Engineer (React Native)', 'Hi Ethan,

Northwind Labs would like to interview you. Expect a message from the recruiter to arrange a time.

You can follow every update in My Applications on Hireloom.', 'app_13', '2026-09-26T05:22:57.668Z'::timestamptz),
  ('ntf_app_13_new', 'usr_recruiter1', 'maya@northwind.test', 'New application: Ethan Brooks for Mobile Engineer (React Native)', 'Hi Maya,

Ethan Brooks applied for Mobile Engineer (React Native). Open My Jobs → View applicants to read their cover note and resume.', 'app_13', '2026-09-22T23:22:57.668Z'::timestamptz),
  ('ntf_app_14_1', 'usr_candidate4', 'rahul@example.test', 'Update on your application for QA Automation Engineer', 'Hi Rahul,

Thank you for applying. Lumen Pay has decided not to move forward with your application this time.

You can follow every update in My Applications on Hireloom.', 'app_14', '2026-09-18T17:10:57.668Z'::timestamptz),
  ('ntf_app_14_new', 'usr_recruiter2', 'arjun@lumen.test', 'New application: Rahul Verma for QA Automation Engineer', 'Hi Arjun,

Rahul Verma applied for QA Automation Engineer. Open My Jobs → View applicants to read their cover note and resume.', 'app_14', '2026-09-16T13:10:57.668Z'::timestamptz),
  ('ntf_app_15_new', 'usr_recruiter2', 'arjun@lumen.test', 'New application: Sofia Martins for Content Strategist', 'Hi Arjun,

Sofia Martins applied for Content Strategist. Open My Jobs → View applicants to read their cover note and resume.', 'app_15', '2026-09-30T11:16:57.668Z'::timestamptz),
  ('ntf_app_16_new', 'usr_recruiter2', 'arjun@lumen.test', 'New application: Ethan Brooks for DevOps Engineer', 'Hi Arjun,

Ethan Brooks applied for DevOps Engineer. Open My Jobs → View applicants to read their cover note and resume.', 'app_16', '2026-09-28T07:52:57.668Z'::timestamptz),
  ('ntf_app_17_1', 'usr_candidate6', 'ethan@example.test', 'Update on your application for Senior Frontend Engineer', 'Hi Ethan,

Thank you for applying. Northwind Labs has decided not to move forward with your application this time.

You can follow every update in My Applications on Hireloom.', 'app_17', '2026-09-28T08:28:57.668Z'::timestamptz),
  ('ntf_app_17_new', 'usr_recruiter1', 'maya@northwind.test', 'New application: Ethan Brooks for Senior Frontend Engineer', 'Hi Maya,

Ethan Brooks applied for Senior Frontend Engineer. Open My Jobs → View applicants to read their cover note and resume.', 'app_17', '2026-09-26T04:28:57.668Z'::timestamptz)
) as v(id, user_id, to_email, subject, body, application_id, created_at)
where exists (select 1 from public."Bhargavi_Job Portal with role-based login_applications" a where a.id = v.application_id)
  and exists (select 1 from public."Bhargavi_Job Portal with role-based login_users" u where u.id = v.user_id)
on conflict do nothing;
