// Writes supabase/seed.sql: demo users, jobs and applications as plain SQL, for pasting into the Supabase
// SQL Editor. The applications' resume PDFs are created in Storage the first time each one is opened.
//   npm run db:seed-sql
import { writeFileSync } from 'fs';
import { buildSeed } from '../lib/seed';
import { TABLES } from '../lib/tables';

const q = (v: string) => `'${v.replace(/'/g, "''")}'`;
const ident = (name: string) => `public."${name}"`;

const { users, jobs, applications } = buildSeed();

const userRows = users
  .map((u) => `  (${[u.id, u.name, u.email, u.passwordHash, u.role, u.createdAt].map(q).join(', ')})`)
  .join(',\n');

const jobRows = jobs
  .map(
    (j) =>
      `  (${[j.id, j.recruiterId, j.title, j.company, j.description, j.location, j.type, j.salary, j.status, j.createdAt, j.updatedAt]
        .map(q)
        .join(', ')})`,
  )
  .join(',\n');

const appRows = applications
  .map(
    (a) =>
      `  (${[a.id, a.jobId, a.candidateId, a.coverNote, a.resumePath, a.resumeName, a.status, a.createdAt, a.updatedAt]
        .map(q)
        .join(', ')})`,
  )
  .join(',\n');

const sql = `-- ════════════════════════════════════════════════════════════════════════════
--  Hireloom · OPTIONAL demo data (users, jobs and job applications)
--
--  Run AFTER schema.sql, in Supabase → SQL Editor. Safe to re-run (existing rows are skipped).
--  Every demo account's password is:  password123
--    Recruiters: ${users.filter((u) => u.role === 'recruiter').map((u) => u.email).join(' · ')}
--    Candidates: ${users.filter((u) => u.role === 'candidate').map((u) => u.email).join(' · ')}
--
--  Resume PDFs for these applications are created in Storage automatically the first time a
--  recruiter or candidate clicks "View resume" — no file upload needed.
--
--  Generated by \`npm run db:seed-sql\` — edit lib/seed.ts, not this file.
-- ════════════════════════════════════════════════════════════════════════════

insert into ${ident(TABLES.users)} (id, name, email, password_hash, role, created_at) values
${userRows}
on conflict do nothing;

insert into ${ident(TABLES.jobs)}
  (id, recruiter_id, title, company, description, location, type, salary, status, created_at, updated_at) values
${jobRows}
on conflict do nothing;

insert into ${ident(TABLES.applications)}
  (id, job_id, candidate_id, cover_note, resume_path, resume_name, status, created_at, updated_at) values
${appRows}
on conflict do nothing;
`;

writeFileSync('supabase/seed.sql', sql);
console.log(`✓ Wrote supabase/seed.sql (${users.length} users, ${jobs.length} jobs, ${applications.length} applications)`);
