// Writes supabase/seed.sql: demo users and jobs as plain SQL, for pasting into the Supabase SQL Editor.
// Applications are left out because each one needs a resume file in Storage (use `npm run db:seed` for those).
//   npm run db:seed-sql
import { writeFileSync } from 'fs';
import { buildSeed } from '../lib/seed';
import { TABLES } from '../lib/tables';

const q = (v: string) => `'${v.replace(/'/g, "''")}'`;
const ident = (name: string) => `public."${name}"`;

const { users, jobs } = buildSeed();

const userRows = users
  .map((u) => `  (${[u.id, u.name, u.email, u.passwordHash, u.role, u.createdAt].map(q).join(', ')})`)
  .join(',\n');

const jobRows = jobs
  .map(
    (j) =>
      `  (${[j.id, j.recruiterId, j.title, j.company, j.description, j.location, j.type, j.salary, j.status, j.createdAt, j.updatedAt]
        .map(q)
        .join(', ')})`,
  )
  .join(',\n');

const sql = `-- ════════════════════════════════════════════════════════════════════════════
--  Hireloom · OPTIONAL demo data (users + jobs)
--
--  Run AFTER schema.sql, in Supabase → SQL Editor. Safe to re-run (existing rows are skipped).
--  Every demo account's password is:  password123
--    Candidates: priya@example.test · daniel@example.test · sofia@example.test
--    Recruiters: maya@northwind.test · arjun@lumen.test
--
--  Generated by \`npm run db:seed-sql\` — edit lib/seed.ts, not this file.
-- ════════════════════════════════════════════════════════════════════════════

insert into ${ident(TABLES.users)} (id, name, email, password_hash, role, created_at) values
${userRows}
on conflict do nothing;

insert into ${ident(TABLES.jobs)}
  (id, recruiter_id, title, company, description, location, type, salary, status, created_at, updated_at) values
${jobRows}
on conflict do nothing;
`;

writeFileSync('supabase/seed.sql', sql);
console.log(`✓ Wrote supabase/seed.sql (${users.length} users, ${jobs.length} jobs)`);
