// Writes supabase/seed.sql: the demo data as plain SQL, for pasting into the Supabase SQL Editor.
// Resume PDFs are created in Storage automatically the first time each one is opened.
//   npm run db:seed-sql
import { writeFileSync } from 'fs';
import { buildSeed } from '../lib/seed';
import { TABLES } from '../lib/tables';

const q = (v: string | null) => (v == null ? 'null' : `'${v.replace(/'/g, "''")}'`);
const arr = (list: string[]) => `array[${list.map(q).join(', ')}]::text[]`;
const ts = (v: string | null) => (v == null ? 'null::timestamptz' : `${q(v)}::timestamptz`);
const ident = (name: string) => `public."${name}"`;
const rows = (list: string[]) => list.map((r) => `  (${r})`).join(',\n');

const { users, jobs, profiles, applications, history, notifications } = buildSeed();

const sql = `-- ════════════════════════════════════════════════════════════════════════════
--  Hireloom · demo data: users, jobs, candidate profiles, applications,
--  status history and notifications
--
--  Run AFTER schema.sql, in Supabase → SQL Editor. Safe to re-run: rows that already
--  exist are skipped. Demo jobs that already exist get their skills and deadline filled in.
--  Every demo account's password is:  password123
--    Recruiters: ${users.filter((u) => u.role === 'recruiter').map((u) => u.email).join(' · ')}
--    Candidates: ${users.filter((u) => u.role === 'candidate').map((u) => u.email).join(' · ')}
--
--  Resume PDFs are created in Storage automatically the first time someone opens one.
--  Generated by \`npm run db:seed-sql\` — edit lib/seed.ts, not this file.
-- ════════════════════════════════════════════════════════════════════════════

-- Users
insert into ${ident(TABLES.users)} (id, name, email, password_hash, role, created_at) values
${rows(users.map((u) => [q(u.id), q(u.name), q(u.email), q(u.passwordHash), q(u.role), ts(u.createdAt)].join(', ')))}
on conflict do nothing;

-- Jobs (existing demo jobs keep their data; only missing skills/deadline are filled in)
insert into ${ident(TABLES.jobs)}
  (id, recruiter_id, title, company, description, location, type, salary, skills, deadline, status, created_at, updated_at) values
${rows(
  jobs.map((j) =>
    [q(j.id), q(j.recruiterId), q(j.title), q(j.company), q(j.description), q(j.location), q(j.type), q(j.salary), arr(j.skills), j.deadline ? `${q(j.deadline)}::date` : 'null', q(j.status), ts(j.createdAt), ts(j.updatedAt)].join(', '),
  ),
)}
on conflict (id) do update set
  skills   = case when cardinality(${ident(TABLES.jobs)}.skills) = 0 then excluded.skills else ${ident(TABLES.jobs)}.skills end,
  deadline = coalesce(${ident(TABLES.jobs)}.deadline, excluded.deadline);

-- Candidate profiles
insert into ${ident(TABLES.candidateProfiles)}
  (user_id, phone, skills, years_experience, resume_path, resume_name, resume_size, updated_at)
select v.* from (values
${rows(profiles.map((p) => [q(p.userId), q(p.phone), arr(p.skills), String(p.yearsExperience), q(p.resumePath), q(p.resumeName), String(p.resumeSize ?? 'null'), ts(p.updatedAt)].join(', ')))}
) as v(user_id, phone, skills, years_experience, resume_path, resume_name, resume_size, updated_at)
where exists (select 1 from ${ident(TABLES.users)} u where u.id = v.user_id)
on conflict do nothing;

-- Applications
insert into ${ident(TABLES.applications)}
  (id, job_id, candidate_id, cover_note, resume_path, resume_name, status, applied_on, updated_at) values
${rows(applications.map((a) => [q(a.id), q(a.jobId), q(a.candidateId), q(a.coverNote), q(a.resumePath), q(a.resumeName), q(a.status), ts(a.createdAt), ts(a.updatedAt)].join(', ')))}
on conflict do nothing;

-- Status history (only for applications that exist)
insert into ${ident(TABLES.statusHistory)} (id, application_id, from_status, to_status, changed_by, changed_at)
select v.* from (values
${rows(history.map((h) => [q(h.id), q(h.applicationId), q(h.fromStatus), q(h.toStatus), q(h.changedBy), ts(h.changedAt)].join(', ')))}
) as v(id, application_id, from_status, to_status, changed_by, changed_at)
where exists (select 1 from ${ident(TABLES.applications)} a where a.id = v.application_id)
  and not exists (select 1 from ${ident(TABLES.statusHistory)} h where h.application_id = v.application_id and h.to_status = v.to_status)
on conflict do nothing;

-- Notifications (email-style log)
insert into ${ident(TABLES.notifications)} (id, user_id, to_email, subject, body, application_id, created_at)
select v.* from (values
${rows(notifications.map((n) => [q(n.id), q(n.userId), q(n.toEmail), q(n.subject), q(n.body), q(n.applicationId), ts(n.createdAt)].join(', ')))}
) as v(id, user_id, to_email, subject, body, application_id, created_at)
where exists (select 1 from ${ident(TABLES.applications)} a where a.id = v.application_id)
  and exists (select 1 from ${ident(TABLES.users)} u where u.id = v.user_id)
on conflict do nothing;
`;

writeFileSync('supabase/seed.sql', sql);
console.log(
  `✓ Wrote supabase/seed.sql (${users.length} users, ${jobs.length} jobs, ${profiles.length} profiles, ${applications.length} applications, ${history.length} history rows, ${notifications.length} notifications)`,
);
